-- function AddTextEntry(key, value)
--   Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
-- end

Citizen.CreateThread(function()
  AddTextEntry("g65amg", "AMG G65")
  AddTextEntry("hcbr17", "CBR 1200RR")
  AddTextEntry("NinjaH2", "Ninja H2R")
  AddTextEntry("sheriff2", "DMAX")
  AddTextEntry("riot", "RIOT")
  AddTextEntry("lguard", "HILUX")
  AddTextEntry("pranger", "RANGER")
  AddTextEntry("baracuda", "BARACUDA POLISI")
  AddTextEntry("INSURGENT2", "Insurgen Polisi")
  AddTextEntry("firetruk", "WATERCANNON")
  AddTextEntry("POLICE", "LANCER x Old")
  AddTextEntry("mazda6", "POLISI MAZDA")
  AddTextEntry("sanchezpol", "Sanchez Polisi")
  AddTextEntry("supraa90", "Supra Mk5")
  AddTextEntry("sclkuz", "LandCruiser") 
  AddTextEntry("r1200rtp", "R1200 Rtp") 
  AddTextEntry("gs1", "BMW GS100 RR")
  AddTextEntry("vxr", "LandCruiser Bintang 4")
  AddTextEntry("psp_bmwgs", "BMWGS 1200")
  AddTextEntry("pbus", "Bus Polisi")
  AddTextEntry("subaru", "Subaru Sti")
  AddTextEntry("raptor2018", "Raptor 6x6")
  AddTextEntry("gsxr", "SUZUKI GSX 1000")
  AddTextEntry("POLBUZZ", "Helicopter Polisi")
  AddTextEntry("CHIRON", "Bugati Polisi")
  AddTextEntry("psp_bmwgs", "BMW1200 RR Polisi")
  AddTextEntry("s15", "Nissan Silvia S15")
  AddTextEntry("tonkatruck", "Tonkat")
  AddTextEntry("fk8", "Honda Civic")
  AddTextEntry("demonhawk", "Jeep Demonhawk")
  AddTextEntry("RIMAC", "Rimac Concept")
  AddTextEntry("nissantitan17 ", "Nissan Titan Warior")
  AddTextEntry("eg6", "Honda Spon Sport")
  AddTextEntry("portpd1", "Dmax v2")
  AddTextEntry("zx10r", "Ninja ZX10R")
  AddTextEntry("zx10", "ZX10")
end)

-- function NamaKendaraan()
--   local ped = GetPlayerPed(-1)
--   local veh = GetVehiclePedIsIn(ped, false)
--   local model = GetEntityModel(veh)
--   local displaytext = GetDisplayNameFromVehicleModel(model)
--   print(displaytext) ----- fungsi utama
-- end